typography_spectrum: 0.5317083039378175
content_rating:
  adult: false
color:
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#FDF400'
    - '#BE0064'
    - '#919191'
  brandStrength: 0.8881177195603268
  lightness: 0.7749961326012185
  saturation: 0.2912613010620422
  rhythmicContrast: 0.740844269854911
github: true
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.5142039905536441
author:
  name: Tommi Enenkel
  url: ''
  email: tommi.enenkel@gmail.com
logo: null
name: Tommi
title: Wahlkampftagebuch
content: []
description: ''
purpose: []
